models:
  - name: users_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCreated
        - from: inputs/rsOrderCancelled
        - from: inputs/rsCartUpdate
  # Remove the section below, if you don't want to generate a feature table
  - name: users
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      macros:
        - name: macro_datediff
          inputs:
            - column
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) {% else %} datediff(day, date({{column}}), GETDATE()) {% endif %}"
        - name: macro_datediff_n
          inputs:
            - column
            - number_of_days
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) <={{number_of_days}} {% else %} datediff(day, date({{column}}), GETDATE()) <= {{number_of_days}} {% endif %}"
      vars:
        - entity_var:
            name: product_used
            from: inputs/rsIdentifies
            select: first_value(product_used ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: The plan the user is currently on
        - entity_var:
            name: viewed_supersonic_content
            from: inputs/rsIdentifies
            select: sum(content_viewed::real)
            description: Number of supersonic content viewed
        - entity_var:
            name: remote_user_score
            from: inputs/rsIdentifies
            select: first_value(remote_user_score ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Confidence score if the user is remote user
        - entity_var:
            name: mwu_user
            from: inputs/rsIdentifies
            select: first_value(mwu_user ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Is the user active with MWU
        - entity_var:
            name: total_sessions_to_date
            from: models/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null
            description: Total individual sessions created till date.
        #days since last seen
        - entity_var:
            name: days_since_last_seen
            select: "{{macro_datediff('max_timestamp_bw_tracks_pages')}}"
            dependencies:
              - max_timestamp_bw_tracks_pages
            description: Days since user last logged in
        - entity_var:
            name: days_since_account_creation
            select: "{{macro_datediff('min(timestamp)')}}"
            from: inputs/rsIdentifies
            description: Number of days since loyaltt account was created
        - entity_var:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value(first_name)
            window:
              order_by:
                - timestamp desc
            where: first_name is not null and first_name!=''
            description: First name of the customer
        - entity_var:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value(last_name)
            window:
              order_by:
                - timestamp desc
            where: last_name is not null and last_name!=''
            description: Last name of the customer
        - entity_var:
            name: recent_user_email
            from: inputs/rsIdentifies
            select: first_value(email)
            window:
              order_by:
                - timestamp desc
            where: email is not null and email!=''
            description: Email associated to the order
        - entity_var:
            name: max_timestamp_tracks
            select: max(timestamp)
            from: inputs/rsTracks
        - entity_var:
            name: max_timestamp_pages
            select: max(timestamp)
            from: inputs/rsPages
            description: The total value of products that are part of the last transaction.
        - entity_var:
            name: max_timestamp_bw_tracks_pages
            select: CASE WHEN max_timestamp_tracks>=max_timestamp_pages THEN max_timestamp_tracks ELSE max_timestamp_pages END
            dependencies:
              - max_timestamp_tracks
              - max_timestamp_pages
              - user_role
      features:
        - product_used
        - viewed_supersonic_content
        - remote_user_score
        - mwu_user
        - first_name
        - last_name
        - recent_user_email
        - total_sessions_to_date
        - days_since_account_creation
        - days_since_last_seen
        - max_timestamp_tracks
        - max_timestamp_pages
        - max_timestamp_bw_tracks_pages
              
