models:
  - name: users_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: users
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - product_used 
        - num_devices_purchased
        - propensity_to_purchase_subscription
        - ltv
        - num_of_open_support_tickets
        - total_sessions_to_date
        - attribution_sources
        - most_recent_email
        - firstname
        - lastname
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: subscription_type
          from: inputs/rsIdentifies
          select: first_value(product_used ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: What type of subscription is the user on
      - entity_var:
          name: num_devices_purchased
          from: inputs/rsIdentifies
          select: sum(devices_purchased::real)
          description: Number of devices purchased
      - entity_var:
          name: propensity_to_purchase_subscription
          from: inputs/rsIdentifies
          select: first_value(remote_user_score ignore nulls)
          window:
            order_by:
              - timestamp desc
      - entity_var:
          name: ltv
          from: inputs/rsIdentifies
          select: first_value(ltv ignore nulls)
          window:
            order_by:
              - timestamp desc
      - entity_var:
          name: propensity_to_churn
          from: inputs/rsIdentifies
          select: right(random(), 2)/100
          description: Likelihood of the user to churn
      - entity_var:
          name: total_sessions_to_date
          from: models/rsTracksUnionPages
          select: uniform(1, 30, random())
          description: Total individual sessions created till date.
      - entity_var:
          name: num_of_open_support_tickets
          from: inputs/rsIdentifies
          select: first_value(open_support_tickets ignore nulls)
          window:
            order_by:
              - timestamp desc
      - entity_var:
          name: attribution_sources
          from: inputs/rsIdentifies
          select: array_agg(array_construct('Google','Facebook','Reddit', 'Bing', 'YouTube')[ABS(MOD(Random(),5))]::text)
          description: All attribution sources in chronological order
      - entity_var:
          name: most_recent_email
          from: inputs/rsIdentifies
          select: first_value(email ignore nulls)
          window:
            order_by:
              - timestamp desc
          where: email is not null and email!=''
          description: Email associated to the user
      - entity_var:
          name: firstname
          from: inputs/rsIdentifies
          select: first_value(first_name ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: First name associated to the user
      - entity_var:
          name: lastname
          from: inputs/rsIdentifies
          select: first_value(last_name ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Last name associated to the user
