models:
  - name: ecomm_loyal_customers_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCreated
        - from: inputs/rsOrderCancelled
        - from: inputs/rsCartUpdate
  # Remove the section below, if you don't want to generate a feature table
  - name: ecomm_loyal_customers
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      macros:
        - name: macro_datediff
          inputs:
            - column
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) {% else %} datediff(day, date({{column}}), GETDATE()) {% endif %}"
        - name: macro_datediff_n
          inputs:
            - column
            - number_of_days
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) <={{number_of_days}} {% else %} datediff(day, date({{column}}), GETDATE()) <= {{number_of_days}} {% endif %}"
      vars:
        - entity_var:
            name: product_interest
            from: inputs/rsIdentifies
            select: array_agg(distinct product_used)
            description: Which content has the user viewed?
        - entity_var:
            name: cardmatch_profile
            from: inputs/rsIdentifies
            select: first_value(cardmatch_profile ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: When is the user looking to sell their home?
        - entity_var:
            name: real_estate_content_viewed
            from: inputs/rsIdentifies
            select: first_value(real_estate_content_viewed ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Number of unique contents viewed about real estate
        - entity_var:
            name: credit_card_content_viewed
            from: inputs/rsIdentifies
            select: first_value(credit_card_content_viewed ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Number of unique contents viewed about credit cards
        - entity_var:
            name: personal_loan_content_viewed
            from: inputs/rsIdentifies
            select: first_value(personal_loan_content_viewed ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Number of unique contents viewed about personal loans
        - entity_var:
            name: total_sessions_to_date
            from: models/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null
            description: Total individual sessions created till date.
        #days since last seen
        - entity_var:
            name: days_since_last_seen
            select: "{{macro_datediff('max_timestamp_bw_tracks_pages')}}"
            dependencies:
              - max_timestamp_bw_tracks_pages
            description: Days since user last logged in
        #Churn features
        - entity_var:
            name: is_churned_7_days
            select: case when days_since_last_seen > 7 then 1 else 0 end
            description: It specifies if there is any activity observed in the last n days. It is dependent on days_since_last_seen
            dependencies:
              - days_since_last_seen
        - entity_var:
            name: days_since_account_creation
            select: "{{macro_datediff('min(timestamp)')}}"
            from: inputs/rsIdentifies
            description: Number of days since loyaltt account was created
        - entity_var:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value(first_name)
            window:
              order_by:
                - timestamp desc
            where: first_name is not null and first_name!=''
            description: First name of the customer
        - entity_var:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value(last_name)
            window:
              order_by:
                - timestamp desc
            where: last_name is not null and last_name!=''
            description: Last name of the customer
        - entity_var:
            name: user_email
            from: inputs/rsIdentifies
            select: first_value(email)
            window:
              order_by:
                - timestamp desc
            where: email is not null and email!=''
            description: Email associated to the order
      features:
        - product_interest
        - cardmatch_profile
        - credit_card_content_viewed
        - real_estate_content_viewed
        - personal_loan_content_viewed
        - total_sessions_to_date
        - days_since_account_creation
        - days_since_last_seen
        - first_name
        - last_name
        - user_email
        - is_churned_7_days

