models:
  - name: ecomm_loyal_customers_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCreated
        - from: inputs/rsOrderCancelled
        - from: inputs/rsCartUpdate
  # Remove the section below, if you don't want to generate a feature table
  - name: ecomm_loyal_customers
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      macros:
        - name: macro_datediff
          inputs:
            - column
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) {% else %} datediff(day, date({{column}}), GETDATE()) {% endif %}"
        - name: macro_datediff_n
          inputs:
            - column
            - number_of_days
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) <={{number_of_days}} {% else %} datediff(day, date({{column}}), GETDATE()) <= {{number_of_days}} {% endif %}"
      vars:
        - entity_var:
            name: intention
            from: inputs/rsIdentifies
            select: array_agg(distinct intention)
            description: What is the user looking to do on OpenDoor?
        - entity_var:
            name: sell_urgency
            from: inputs/rsIdentifies
            select: first_value(sell_urgency ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: When is the user looking to sell their home?
        - entity_var:
            name: buy_urgency
            from: inputs/rsIdentifies
            select: first_value(buy_urgency ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: When is the user looking to buy a home?
        - entity_var:
            name: total_sessions_to_date
            from: models/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null
            description: Total individual sessions created till date.
        - entity_var:
            name: max_timestamp_cart_update
            select: max(timestamp)
            from: inputs/rsCartUpdate
        - entity_var:
            name: days_since_last_cart_add
            select: "{{macro_datediff('max_timestamp_cart_update')}}"
            description: Number of days since the user has added a product to cart
            dependencies:
              - max_timestamp_cart_update
        - entity_var:
            name: max_timestamp_tracks
            select: max(timestamp)
            from: inputs/rsTracks
        - entity_var:
            name: max_timestamp_pages
            select: max(timestamp)
            from: inputs/rsPages
            description: The total value of products that are part of the last transaction.
        - entity_var:
            name: max_timestamp_bw_tracks_pages
            select: CASE WHEN max_timestamp_tracks>=max_timestamp_pages THEN max_timestamp_tracks ELSE max_timestamp_pages END
            dependencies:
              - max_timestamp_tracks
              - max_timestamp_pages
        #days since last seen
        - entity_var:
            name: days_since_last_seen
            select: "{{macro_datediff('max_timestamp_bw_tracks_pages')}}"
            dependencies:
              - max_timestamp_bw_tracks_pages
            description: Days since user last logged in
        #Churn features
        - entity_var:
            name: is_churned_7_days
            select: case when days_since_last_seen > 7 then 1 else 0 end
            description: It specifies if there is any activity observed in the last n days. It is dependent on days_since_last_seen
            dependencies:
              - days_since_last_seen
              #days since last purchase
        - entity_var:
            name: max_timestamp_order_created
            select: max(timestamp)
            from: inputs/rsOrderCreated
            description: Last purchase date
        - entity_var:
            name: days_since_last_purchase
            select: "{{macro_datediff('max_timestamp_order_created')}}"
            description: Number of days since the user purchased the latest product
            dependencies:
              - max_timestamp_order_created
        #days since first purchase
        - entity_var:
            name: min_timestamp_order_created
            select: min(timestamp)
            from: inputs/rsOrderCreated
        - entity_var:
            name: days_since_first_purchase
            select: "{{macro_datediff('min_timestamp_order_created')}}"
            description: Number of days since the user purchased the first product
            dependencies:
              - min_timestamp_order_created
        #has credit card
        - entity_var:
            name: has_credit_card
            select: max(case when lower(payment_details_credit_card_company) in ('visa','american express','mastercard') then 1 else 0 end)
            from: inputs/rsOrderCreated
            description: If the user has a credit card.
        #avg_units_per_transaction
        - entity_var:
            name: avg_units_per_transaction
            select: avg({{ array_size ( 'products' )}}::real)
            from: inputs/rsOrderCreated
            description: It shows the average units purchased in each transaction. (Total units in each transaction/Total transactions). Includes only those transactions where the total price (from column current_total_price) is greater than zero. So, the feature exclude transactions with 100% off, replacement products etc that may result in the total_price being equal to zero.
        #avg_transaction_value
        - entity_var:
            name: avg_transaction_value
            select: avg( total_price_usd ::real)
            from: inputs/rsOrderCreated
            description: Total price in each transaction/Total number of transactions.
        #highest_transaction_value
        - entity_var:
            name: highest_transaction_value
            select: max(total_price_usd ::real)
            from: inputs/rsOrderCreated
            description: Of all the transactions done by the user, this features contains the highest transaction value.
        #median_transaction_value
        - entity_var:
            name: median_transaction_value
            select: median( total_price_usd ::real)
            from: inputs/rsOrderCreated
            description: Median value of total price of all the transactions
        #total_transactions
        - entity_var:
            name: total_transactions
            select: count(*)
            from: inputs/rsOrderCreated
            description: Total number of transactions done by the user
        - entity_var:
            name: last_transaction_value
            from: inputs/rsOrderCreated
            select: first_value(total_price_usd)
            window:
              order_by:
                - case when TOTAL_PRICE_USD is not null then 2 else 1 end desc
                - timestamp desc
            description: The total value of products that are part of the last transaction.
        - entity_var:
            name: days_since_account_creation
            select: "{{macro_datediff('min(timestamp)')}}"
            from: inputs/rsIdentifies
            description: Number of days since loyaltt account was created
        - entity_var:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value(first_name)
            window:
              order_by:
                - timestamp desc
            where: first_name is not null and first_name!=''
            description: First name of the customer
        - entity_var:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value(last_name)
            window:
              order_by:
                - timestamp desc
            where: last_name is not null and last_name!=''
            description: Last name of the customer
        - entity_var:
            name: user_email
            from: inputs/rsIdentifies
            select: first_value(email)
            window:
              order_by:
                - timestamp desc
            where: email is not null and email!=''
            description: Email associated to the order
        - entity_var:
            name: total_carts
            select: count(distinct token)
            from: inputs/rsCartUpdate
            description: Total carts created by the user till date.
        - entity_var:
            name: total_products_added
            select: array_agg(distinct product_id)
            from: models/rsCartLineItems
            description: Total products added to cart till date. (array with list of all product ids). It includes all purchased products plus current active cart.
        - entity_var:
            name: products_added_in_past_1_days
            select: array_agg(distinct product_id)
            from: models/rsCartLineItems
            where: "{{macro_datediff_n('timestamp','1')}}"
            description: List of products added to cart by the user in last 1 days. (array with list of all product ids). It includes all purchased products plus current active cart.
        - entity_var:
            name: products_added_in_past_7_days
            select: array_agg(distinct product_id)
            from: models/rsCartLineItems
            where: "{{macro_datediff_n('timestamp','7')}}"
            description: List of products added to cart by the user in last 7 days. (array with list of all product ids). It includes all purchased products plus current active cart.
        - entity_var:
            name: products_added_in_past_365_days
            select: array_agg(distinct product_id)
            from: models/rsCartLineItems
            where: "{{macro_datediff_n('timestamp',365)}}"
            description: List of products added to cart by the user in last 365 days. (array with list of all product ids). It includes all purchased products plus current active cart.
        - entity_var:
            name: latest_cart_id
            from: models/rsCartLineItems
            select: first_value(token)
            window:
              order_by:
                - timestamp desc
            description: Last known cart id
        - entity_var:
            name: transactions_in_past_1_days
            select: count(*)::real
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','1')}}"
            description: Number of transactions in last 1 day
        - entity_var:
            name: transactions_in_past_90_days
            select: count(*)::real
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','90')}}"
            description: Number of transactions in last 90 day
        - entity_var:
            name: transactions_in_past_365_days
            select: count(*)::real
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','365')}}"
            description: Number of transactions in last 365 day
        - entity_var:
            name: net_amt_spent_in_past_90_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','90')}}"
            description: Net amount i.e. sales-refund spent by the user in last 90 days.
        - entity_var:
            name: net_amt_spent_in_past_365_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','365')}}"
            description: Net amount i.e. sales-refund spent by the user in last 365 days.
        - entity_var:
            name: net_amt_spent_in_past_1_days
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: models/rsOrderCreatedOrderCancelled
            where: "{{macro_datediff_n('timestamp','1')}}"
            description: Net amount i.e. sales-refund spent by the user in last 1 day.
        - entity_var:
            name: net_amt_spent_in_past
            select: sum(total_price_usd::real) - coalesce(sum(total_price_usd_order_cancelled::real), 0)
            from: models/rsOrderCreatedOrderCancelled
            description: Net amount i.e. sales-refund spent by the user to date.
        - entity_var:
            name: gross_amt_spent_in_past
            select: sum(total_price_usd::real)
            from: models/rsOrderCreatedOrderCancelled
            description: Total value of products purchased till date.
        - entity_var:
            name: items_purchased_ever
            select: array_agg(sku)
            from: models/rsItemsPurchasedEver
            description: The list of unique products bought by the user.
      features:
        - intention
        - sell_urgency
        - buy_urgency
        - total_sessions_to_date
        - days_since_account_creation
        - days_since_last_seen
        - first_name
        - last_name
        - user_email
        - last_transaction_value
        - highest_transaction_value
        - median_transaction_value
        - avg_transaction_value
        - total_transactions
        - is_churned_7_days
        - days_since_last_cart_add
        - days_since_last_purchase
        - days_since_first_purchase
        - has_credit_card
        - avg_units_per_transaction
        - total_carts
        - total_products_added
        - products_added_in_past_1_days
        - products_added_in_past_7_days
        - products_added_in_past_365_days
        - transactions_in_past_1_days
        - transactions_in_past_90_days
        - transactions_in_past_365_days
        - net_amt_spent_in_past_1_days
        - net_amt_spent_in_past_90_days
        - net_amt_spent_in_past_365_days
        - net_amt_spent_in_past
        - gross_amt_spent_in_past
        - items_purchased_ever
